baseURL = 'https://openstreetmap.be/'
defaultContentLanguage = 'en'
enableEmoji = true
summaryLength = 50
uglyURLs = true

[frontmatter]
  date = [':filename', ':default']

[markup.highlight]
  style = 'catppuccin-macchiato'
  lineNos = true
  lineNumbersInTable = false
[markup.goldmark.parser.attribute]
  block = true

[outputs]
  home = ['html', 'json']

[permalinks]
  [permalinks.page]
    posts = '/:year/:month/:day/:slug'

[security.funcs]
  getenv = ['STADIA_API_KEY']